# Header
author: 'JWSingle'
subtitle: 'è®¤çœŸçš„äººæ‰æœ‰èµ„æ ¼å¼€ç©ç¬‘@_@'


# å¤´åƒurl
avatar: '/img/touxiang.jpg'
# å¤´åƒæ˜¯å¦æ—‹è½¬
avatarrotation: true
# ç½‘ç«™å›¾æ ‡
favicon: 'img/favicon.ico'


# left-colä¾§æ 
menu:
#  ä¸»é¡µ: /
#  å½’æ¡£: archives/index.html
#  åˆ†ç±»: categories/index.html
#  ç›¸å†Œ: photos/index.html
#  éŸ³ä¹: music/index.html
  ä¸»é¡µ: /
  å½’æ¡£: archives/index.html
  åˆ†ç±»: categories/index.html
  ç›¸å†Œ: photos/index.html
  éŸ³ä¹: music/index.html
  å…³äºæˆ‘: about/index.html
  
# SubNav
subnav:
  github: "https://github.com/jiangjiawei520"
  #gitee: "#"
  csdn: "https://blog.csdn.net/wei2314857815"
  # weibo: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #rss: "atom.xml"
  #mail: "mailto:XXX@XXX.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  #steam: "#"
  #cc: "#"
  #wikipedia: "#"
  #gitlab: "#"
  #telegram: "#"
  #youtube: "#"
  #stackoverflow: "#"
  #whatsapp: "#"
  #instagram: "#"

  
# ç½‘æ˜“äº‘éŸ³ä¹æ’ä»¶
music:
  enable: true
  id: 1459950258   # ç½‘æ˜“äº‘åˆ†äº«çš„ID
  autoplay: false  # æ˜¯å¦å¼€å¯è‡ªåŠ¨æ’­æ”¾
  # æç¤ºæ–‡æœ¬(å…³é—­è¯·è®¾ç½®ä¸ºfalse)
  text: 'è¿™ä¼¼ä¹æ˜¯å¥½å¬éŸ³ä¹ï¼Œè¯·å°½æƒ…çš„æ¬£èµå®ƒå§ï¼'

# APlayeræ’­æ”¾å™¨
# https://aplayer.js.org/
aplayer:
  enable: false
  
# ä¾§æ æ—¶é’Ÿ
clock:
  enable: true

# é¼ æ ‡ç‰¹æ•ˆ
mouse:
  love: true
  word: false
  
# é›ªèŠ±ç‰¹æ•ˆ 
# å¼€å¯åæœ‰äº›å¡
snow:
  enable: false
  

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›,å‚è€ƒhttp://gradientsguru.com/
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  #header: '#4d4d4d'
  header: 'linear-gradient(55deg,#88ACDB,#49B1F5,#9534f1,#49b1f5)'
  # å³æ»‘æ¿å—èƒŒæ™¯
  #slider: 'linear-gradient(55deg,#88ACDB,#49B1F5,#9534f1,#49b1f5)'
  slider:  'linear-gradient(to right,  #9999a4 0%,#60606b 100%)'
  # å¥½çœ‹çš„èƒŒæ™¯é¢œè‰²
  # 'linear-gradient(45deg, #2196f3, #c974f5)'
  # 'linear-gradient(200deg,#ccc,#000)'
  # 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  # 'linear-gradient(45deg, #c053f7, #23a2ed)'
  # 'linear-gradient(to right,  #9999a4 0%,#60606b 100%)'


# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: true

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  link:
    #éšç¬”: /tags/éšç¬”/
    #å¼€å¾€: https://www.foreverblog.cn/go.html
  menu:
    innerArchive: 'æ‰€æœ‰æ–‡ç« '
    friends: 'å‹é“¾'
    aboutme: 'å…³äºæˆ‘'

friends:
  ä¸‰æ°´ã®Blog: https://sanshui.findn.cn/
  ä¸‰æ°´çš„ç¬”è®°: https://findn.cn/
  æŠ€æœ¯ç¬”è®°: https://zhousiwei.gitee.io/ibooks/
  GitHub: https://github.com/JoeyBling
  CSDN: https://blog.csdn.net/qq_30930805
  è·å¡˜æœˆè‰²: https://yansheng836.github.io/

aboutme: ğŸ‘‹ğŸ‘‹å…³äºJWSingle<br>ğŸŒ±JWSingleæ˜¯ä¸€ä¸ªä¸ªäººç«™ã€‚<br>ğŸ˜‰ğŸ˜‰å¯¹åšå®¢çš„ç†è§£<br>âœ¨å–œæ¬¢å†™Blogçš„äººï¼Œä¼šç»å†ä¸‰ä¸ªé˜¶æ®µã€‚<br>ğŸŒç¬¬ä¸€é˜¶æ®µï¼Œåˆšæ¥è§¦Blogï¼Œè§‰å¾—å¾ˆæ–°é²œï¼Œè¯•ç€é€‰æ‹©ä¸€ä¸ªå…è´¹ç©ºé—´æ¥å†™ã€‚<br>ğŸŒ‹ç¬¬äºŒé˜¶æ®µï¼Œå‘ç°å…è´¹ç©ºé—´é™åˆ¶å¤ªå¤šï¼Œå°±è‡ªå·±è´­ä¹°åŸŸåå’Œç©ºé—´ï¼Œæ­å»ºç‹¬ç«‹åšå®¢ã€‚<br>ğŸ’¬ç¬¬ä¸‰é˜¶æ®µï¼Œè§‰å¾—ç‹¬ç«‹åšå®¢çš„ç®¡ç†å¤ªéº»çƒ¦ï¼Œæœ€å¥½åœ¨ä¿ç•™æ§åˆ¶æƒçš„å‰æä¸‹ï¼Œè®©åˆ«äººæ¥ç®¡ï¼Œè‡ªå·±åªè´Ÿè´£å†™æ–‡ç« ã€‚<br><br>ğŸ˜„ğŸ˜„Why Blog<br>ğŸš¥æˆ‘ä»¬æ¯ä¸ªäººçš„åœ¨ç½‘ç»œä¸Šäº§ç”Ÿçš„æ•°æ®è¶Šæ¥è¶Šå¤šï¼Œè¿™äº›ä¿¡æ¯æ˜¯æˆ‘ä»¬åœ¨äº’è”ç½‘ä¸Šå­˜åœ¨è¿‡çš„ç—•è¿¹ï¼Œå€¼å¾—æˆ‘ä»¬è®¤çœŸå¯¹å¾…ã€‚ä½†æ˜¯å®ƒä»¬è¢«åˆ†æ•£åˆ†å¸ƒåœ¨å„ä¸ªç½‘ç«™ä¸Šã€‚å¾ˆå¤šæ—¶å€™æˆ‘ä»¬å¾ˆéš¾å°†å®ƒä»¬èšåˆåœ¨ä¸€èµ·ï¼Œè€Œä¸”å„ä¸ªç½‘ç«™çš„ä¿¡æ¯æ’å¸ƒæ–¹å¼ä¹Ÿæ²¡æœ‰åŠæ³•è‡ªç”±æ§åˆ¶ï¼Œæ‰€ä»¥æˆ‘ä»¬éœ€è¦ä¸€ä¸ªå¯ä»¥ç”±è‡ªå·±ä¸»å®°çš„ç©ºé—´â€”â€”åšå®¢ã€‚<br>


# ä¸€è¨€
yiyan:
  enable: true
  
  
# Content

# æ˜¯å¦å¼€å¯å­—æ•°ç»Ÿè®¡
# ä¸éœ€è¦ä½¿ç”¨ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
word_count: true
# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—ï¼Œæ–‡ç« é‡Œé¢æ·»åŠ <!--more-->
# excerpt_link: 'more'
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'

# æ˜¯å¦å¼€å¯åˆ†ç±»çš„æ ‡ç­¾
category_tag: true
# æ˜¯å¦å¼€å¯æ–‡ç« ä¸‹çš„æ ‡ç­¾
article_tag: true

# æ•°å­¦å…¬å¼
mathjax: true

# éœ€è¦å£°æ˜ä¸ºâ€œåŸåˆ›â€çš„æ–‡ç« å¼€å¤´å†™ä¸Šarticle_type: 0,â€œè½¬è½½â€åˆ™æ˜¯article_type: 1
article_type: false

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# æ‰“èµ
reward:
  enable: false
  # æ‰“èµæ ·å¼ 1 and 2
  type: 2
  # æ‰“èµwording
  wording: 'æ„Ÿè§‰ä¸é”™ æ”¯æŒä¸€ä¸‹'
  # æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
  alipay: 'img/alipay-min.png'
  # å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
  weixin: 'img/wechatpay-min.png'


# ç›®å½•
toc: true
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: false
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'å“¦ï¼Œç›®å½•ä¸å­˜åœ¨'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: false

# ç‰ˆæƒå£°æ˜
#åœ¨ä¸éœ€è¦è¿›è¡Œç‰ˆæƒå£°æ˜çš„æ–‡ç« çš„m dæ–‡ä»¶å¤´éƒ¨ï¼Œè®¾ç½®å±æ€§ no_declare: true
declare:
  enable: false
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/          #å½“å‰åº”ç”¨çš„ç‰ˆæƒåè®®åœ°å€ã€‚
  licensee_name: 'CC BY-NC-SA 4.0'                                          #ç‰ˆæƒåè®®çš„åç§°
  licensee_alias: 'çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…è®¸å¯åè®®' # aliasåˆ«å
  # licensee_img: 'https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png'    #[å¯é€‰]ç‰ˆæƒåè®®çš„Logoé“¾æ¥ 


#è¯„è®ºï¼š1ã€walineï¼›2ã€gittalkï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰

#1ã€waline
# [Waline](https://waline.js.org) 
# å‚è€ƒä¸Šé¢åœ°å€ æ¶‰åŠå†…å®¹LeanCloudï¼ˆhttps://console.leancloud.app/appsï¼‰ ã€githubï¼ˆperson_blog_new_commentï¼‰ã€Vercelï¼ˆhttps://vercel.com/jiangjiawei520s-projectsï¼‰ã€åŸŸåè½¬æ¢ï¼ˆé˜¿é‡Œäº‘ï¼‰
# 
waline:
  enable: false
  server_url: 'https://comment.jiangjiawei.xyz'  #https://person-blog-new-comment-k0xzkxrci-jiangjiawei520s-projects.vercel.app/ç»è¿‡åŸŸåæ˜ å°„ï¼Œå¦åˆ™ä¼šæœ‰è·¨åŸŸé—®é¢˜ï¼Œæ— æ³•ä½¿ç”¨ï¼ˆéœ€è¦æ¢¯å­ï¼Œä¸ç„¶æ— æ³•ä½¿ç”¨ï¼Œæœªè§£å†³ï¼Œä¸ä½¿ç”¨ï¼‰
  login: 'enable'       # 'enable': å¯ç”¨ç™»å½• (é»˜è®¤) 'disable': ç¦ç”¨ç™»å½•ï¼Œç”¨æˆ·åªèƒ½å¡«å†™ä¿¡æ¯è¯„è®º 'force': å¼ºåˆ¶ç™»å½•ï¼Œç”¨æˆ·å¿…é¡»æ³¨å†Œå¹¶ç™»å½•æ‰å¯å‘å¸ƒè¯„è®º
  lang: 'zh-CN '        # è¯­è¨€ï¼Œé»˜è®¤'zh-CN', 'en'/ 'jp'å¯é€‰
  dark: ''              # è®¾ç½® 'auto' ä¼šæ ¹æ®è®¾å¤‡æš—é»‘æ¨¡å¼è‡ªé€‚åº”ã€‚
  word_limit: 0         # è¯„è®ºå­—æ•°é™åˆ¶ï¼Œ0ä¸ºä¸é™åˆ¶ï¼Œé»˜è®¤å€¼ä¸º0
  page_size: 10         # è¯„è®ºåˆ—è¡¨åˆ†é¡µï¼Œæ•°å­—ä¸ºæ¡æ•°ï¼Œé»˜è®¤å€¼10
  image_uploader: false # ä½ å¯ä»¥è®¾ç½®ä¸º false ä»¥ç¦ç”¨å›¾ç‰‡ä¸Šä¼ åŠŸèƒ½
  pageview: true        # æ˜¯å¦å¼€å¯æ–‡ç« è®¿é—®é‡ç»Ÿè®¡

#2ã€gittalk å‚è€ƒhttps://blog.csdn.net/weixin_42691420/article/details/102761576
gittalk: 
  enable: false
  clientID: '16fa9741c35e4c6bd5ce' #æ³¨å†Œæ—¶çš„id
  clientSecret: '3d71d2e15cc431d7146cfa52d0b0a2fb8a1ef422' #æ³¨å†Œæ—¶çš„secret
  repo: 'person_blog_new_comment' #githubæ–°å»ºçš„Repository name
  owner: 'jiangjiawei520' #githubçš„ç”¨æˆ·åï¼Œä¸ç”¨æ”¹æˆå°å†™
  admin: ['jiangjiawei520']


#3ã€ç•…è¨€
# å¹¿å‘Šæœ‰ç‚¹å¤š
changyan_appid: false
changyan_conf: false

#4ã€Disqus
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: 'person_blog_new'          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: '16fa9741c35e4c6bd5ce'           #client ID
  client_secret: 'a78bb155405ec337cbfd47ee2af4d93d9e694baf'       #client secret


#6ã€Valine https://valine.js.org,å‚è€ƒhttps://github.com/litten/hexo-theme-yilia/pull/646å’Œhttp://t.csdnimg.cn/RqBU8
valine_type: 2 #0 å…³é—­è¯„è®º  2å…¨å¼€è¯„è®º  1éœ€è¦å†æ–‡ç« mdå¼€å¤´åŠ å…¥valineenbale:true
valine: 
 enable: true
 appid: oaNIM7WrQSG7UOdJT8sGT8Ap-gzGzoHsz #Leancloudåº”ç”¨çš„appId
 appkey: CnYOpc2uW5oBwt6wgLB1ggYh #Leancloudåº”ç”¨çš„appKey
 verify: true #éªŒè¯ç 
 notify: true #è¯„è®ºå›å¤æé†’
 avatar: wavatar #è¯„è®ºåˆ—è¡¨å¤´åƒæ ·å¼ï¼š''/mm/identicon/monsterid/wavatar/retro/hide
 placeholder: ãƒ¾ï¾‰â‰§âˆ€â‰¦)oæ¥å•Šï¼Œå¿«æ´»å•Š! 
 guest_info: nick,mail,link # custom comment header
 pageSize: 10 # pagination size



# é¡µè„šä¿¡æ¯
footer:
  enable: true
  show_busuanzi: true
  show_create_time: true
  create_year: '2020'
  create_time: '01/01/2020 00:00:00'
  #icp: 'é™•ICPå¤‡XXXå·'
  theme_info: false
  youpaiyun: false


# SEOä¼˜åŒ–

# ç™¾åº¦ç»Ÿè®¡
# https://tongji.baidu.com/
baidu_analytics:
  enable: false
  id: ''
  
# è°·æ­Œåˆ†æ  
# http://analytics.google.com/analytics/web/
google_analytics:
  enable: false
  id: ''
  
# ç™¾åº¦ç«™é•¿å¹³å°jsè‡ªåŠ¨æ¨é€(https://ziyuan.baidu.com/linksubmit/index)
# é¡µé¢è¢«è®¿é—®äº†ï¼Œå°±ä¼šè¢«æ¨é€è¿‡å»ã€‚
# ç›®å‰jsè‡ªåŠ¨æ¨é€å·²ç»è¢«ç™¾åº¦å–æ¶ˆ
baidu_push: false

search:
  path: search.xml
  field: all

# Tab Title Change | æ ‡ç­¾é¡µæ ‡é¢˜åˆ‡æ¢
tab_title_change:
  enable: true
  left_tab_title: '(ã¤ã‚§âŠ‚) æˆ‘è—å¥½äº†å“¦~ '
  return_tab_title: '(*Â´âˆ‡ï½€*) è¢«ä½ å‘ç°å•¦~ '